### ISSUE TITLE
[Original Ally] - Broken Rainbow RGB (Fix in issue)

### ISSUE THREAD

**Issue by Bladen123** [ublue-os/bazzite#1153]
# Bazzite Dev Note:
**Fix can be found here: https://github.com/ublue-os/bazzite/issues/1153#issuecomment-2322934767**

# -----------------------------------------------------------------------------------

### Describe the bug

I installed BazziteOS used that for some hours to test my games , after that i reinstalled windows 11 and armory crate every thing seems to work normal beside the RGB Rainbow , the RGB works as solid color or whatever i want also the aura sync works and the modes too. Only that doesnt work is the standard Rainbow RGB if i choos that the rgb is off like no light.

### What did you expect to happen?

Normaly isnt first time i used bazziteOS , last time was kind similar but instad rgb are like OFF was red light only until i reinstalled windows and armory crate after that my rgb worked normal as should even the rainbow color. so i expected to work after fresh windows install , but this time it doesnt i feel like something happend with the latest bazzite OS updates.

### Hardware

ROG ALLY Z1 Extreme

**Comment by antonyho** [comment]
Having the same situation.
And there are occurrences that the right stick has RGB light on, and the left stick has light off when a mode has something wrong. There are some new modes on the Armoury Crate now. They all don't work.


![image](https://github.com/ublue-os/bazzite/assets/2982107/1a7461a6-8ad8-487e-a96b-ef673cb82ece)

**Comment by mrwhistles** [comment]
This happened to me as well. This is what I did:

In windows/Armory Crate I turned off all LEDs for all situations. At this point the "rainbow" option didn't work at all except through aura sync.
I rebooted into bazzite and rolled back to a previous release (bazzite-rollback-helper rebase 40-20240427)
Booted windows, turned LEDs back on and now everything is back to normal and I can enable the "rainbow" visual.

**Comment by antheas** [comment]
Im adding Rainbow support to hhd and noticed it was broken, care to expand?

**Comment by antheas** [comment]
![image](https://github.com/ublue-os/bazzite/assets/5252246/73390e18-ad82-4f0b-ad84-d49040fe0d1b)

so you say 7 is the image that works and this commit was made on the 8th ey?

**Comment by KyleGospo** [comment]
Closed for no response

**Comment by antheas** [comment]
It's a major bug, reopen

**Comment by KyleGospo** [comment]
> It's a major bug, reopen

Commenting here due to most discussion being in discord. I believe the current status is we've fixed this and are looking for a way to restore existing broken RGB, is that correct?

**Comment by antheas** [comment]
Yes, only Allys that used an image in May are affected. We have found and fixed the bug that we suspected and most of our current testers have working rainbow RGB in Bazzite (called spiral in Handheld Daemon).

Next Handheld Daemon version adds a more indepth initialization which may help with fixing the affected devices as well, but we have not verified this yet.

We are looking for additional testers though so reach out, especially if you are affected.

**Comment by antheas** [comment]
I also maintain an image here which is based on the 0427 image that is known to fix the issue and is not close to expiring https://github.com/hhd-dev/bazzite-dc

**Comment by Harithz001** [comment]
> I also maintain an image here which is based on the 0427 image that is known to fix the issue and is not close to expiring https://github.com/hhd-dev/bazzite-dc

Tried rebasing to this image, the spiral rgb worked in bazzite but windows rainbow led still is broke. I then tried disabling led support on hhd and reinstall windows through cloud recovery but this does not fix the rainbow led in windows.

**Comment by Kylorenzzz** [comment]
> I also maintain an image here which is based on the 0427 image that is known to fix the issue and is not close to expiring https://github.com/hhd-dev/bazzite-dc

Tried this and does not work. Bazzite broke my rainbow rgb too. And it's such bad timing as I am receiving my Ally X in a few days yet I am stuck as I could not re-sell my device due to the broken rgb lights. Pls help!!!

**Comment by Evilexium** [comment]
> Yes, only Allys that used an image in May are affected. We have found and fixed the bug that we suspected and most of our current testers have working rainbow RGB in Bazzite (called spiral in Handheld Daemon).
> 
> Next Handheld Daemon version adds a more indepth initialization which may help with fixing the affected devices as well, but we have not verified this yet.
> 
> We are looking for additional testers though so reach out, especially if you are affected.

Before this New BazziteOS came out that broke even more of the rogs , we just did rebase to i think 39-20240406 and that fixed the rgb , now even that doesnt fix it and my controller isnt recognized by bios anymore since i rebased to this https://github.com/hhd-dev/bazzite-dc

**Comment by antheas** [comment]
Yes, there is a missing initialization command in the current version.

If you guys can run the following command:
```
curl https://raw.githubusercontent.com/hhd-dev/hhd/master/local_hhd.sh | sh
``` 

If the old image fixed this this will as well.

**Comment by antheas** [comment]
In any case, I am working with an ally right now and I should have a solution to this today.

**Comment by antheas** [comment]
I pushed a version that fixes the RGB initialization bug that got introduced in the Ally X version.

https://github.com/hhd-dev/hhd/releases/tag/v3.2.2

**Comment by antheas** [comment]
bazzite-dc is updated with the new Handheld Daemon version that does the proper init. Hopefully it helps.

We also tried booting into one of the bazzite images that had the issue and the rainbow mode worked there and then worked in windows as well.

**Comment by Evilexium** [comment]
Will give a Try and will post soon here back. Thank you Antheas for all this extreme efforts u invest into this

**Comment by antheas** [comment]
That command installs the new version until you reboot, which you're going to get it eventually on CachyOS.

I do not think CachyOS was affected by the bug (yet)

**Comment by Yqw175** [comment]
curl https://raw.githubusercontent.com/hhd-dev/hhd/master/local_hhd.sh | sh
rpm-ostree rebase ostree-unverified-registry:ghcr.io/hhd-dev/bazzite-dc:stable

The above two tests did not fix the rainbow

**Comment by antheas** [comment]
We have had at least 4 people with working spiral mode still show that it is working in the current version. Including one verifying it in windows.

Therefore, the issue does not happen in current images and the question becomes how reset current devices.

Searching online there does not seem to be a way to reset the MCU, so we need to look into how to do that.

The legion go, for example, has at least 2 ways to reset its controllers.

**Comment by antheas** [comment]
Is it fair to assume all of you guys are both on the latest bios (339) and controller firmware?

**Comment by SuperSirLink** [comment]
if it helps, I have encountered a similar issue with the RGB/Spiral setting, I did not have Bazzite installed, but did have Nobara 40 and I was trying to follow the instructions to install Nvidia drivers and asusctl and supergfxctl per the Asus-linux.org page.  Noticed the went dark at some point, reboot to Windows (on an external drive) and found I still didn't have the rainbow setting come on.  all the other modes work fine.

**Comment by KyleGospo** [comment]
> if it helps, I have encountered a similar issue with the RGB/Spiral setting, I did not have Bazzite installed, but did have Nobara 40 and I was trying to follow the instructions to install Nvidia drivers and asusctl and supergfxctl per the Asus-linux.org page.  Noticed the went dark at some point, reboot to Windows (on an external drive) and found I still didn't have the rainbow setting come on.  all the other modes work fine.
> 
> I am also on the latest bios and current firmware

That tracks, we've suspected this is software that we don't write causing this. 

Very much appreciate the info, hopefully we find a solution to fix devices already affected by this soon.

**Comment by SuperSirLink** [comment]
I will also note that I am running the latest version of HHD when installing from:
curl -L https://github.com/hhd-dev/hhd/raw/master/install.sh | bash

**Comment by Evilexium** [comment]
> Is it fair to assume all of you guys are both on the latest bios (339) and controller firmware (V317)?

Yes i am , still didnt worked all the attempts i got here to try

**Comment by Evilexium** [comment]
> if it helps, I have encountered a similar issue with the RGB/Spiral setting, I did not have Bazzite installed, but did have Nobara 40 and I was trying to follow the instructions to install Nvidia drivers and asusctl and supergfxctl per the Asus-linux.org page. Noticed the went dark at some point, reboot to Windows (on an external drive) and found I still didn't have the rainbow setting come on. all the other modes work fine.
> 
> I am also on the latest bios and current firmware

That was allways like this , on windows allways worked all even aura , was months ago same , what we want is the rainbow on windows back

**Comment by SuperSirLink** [comment]
> > if it helps, I have encountered a similar issue with the RGB/Spiral setting, I did not have Bazzite installed, but did have Nobara 40 and I was trying to follow the instructions to install Nvidia drivers and asusctl and supergfxctl per the Asus-linux.org page. Noticed the went dark at some point, reboot to Windows (on an external drive) and found I still didn't have the rainbow setting come on. all the other modes work fine.
> > I am also on the latest bios and current firmware
> 
> That was allways like this , on windows allways worked all even aura , was months ago same , what we want is the rainbow on windows back

No what I am saying is if I reboot into windows, I RGB works on any mode including Aura, except Rainbow.  The leds remain off.

**Comment by SuperSirLink** [comment]
I installed Bazzite and can confirm that did not fix the issue.

**Comment by antheas** [comment]
In-between my previous message, we also tried a variety of other fixes that also did not work. The local_hhd uses the latest Handheld Daemon version until reboot, where I tried to include additional LED fixes that seem to not help. Bazzite will include the latest version later today, so you can stop using it now.

We have reached out to Asus for the issue. I will keep the thread up to date as we receive more information.

In any case, I also heard that the Ally had this problem in a worse form in Windows early post launch, where none of the LEDs would work outside Aura mode. So it is a firmware quirk that is easily fixable with a firmware update.

As it is holidays in most of the world and they are working professionals, it might take a while for a fix to trickle down to Windows and Linux. So I would advise some patience.


I will re-iterate that the current versions of Bazzite do not cause this issue. This has been tested on both on the original Ally and Ally X. It is also unclear the previous versions did, as we tried to break the rainbow mode on an Ally by using one of those builds and could not.

In addition, I have personally vetted every single command that gets sent to the MCU through Handheld Daemon, which did not change commands since January and June so it could not have caused this, and it has always logged every single MCU LED command it sends.

I have overseen kernel changes in Bazzite that disable the kernel module asus_hid for the Ally and we deprecated the Ally image one month ago, which contained third party code that could be used to control the Ally not vetted by us. 

If any of you are on the Ally image, it is recommended to switch to the Deck image using one of the following (depending on your Desktop Environment):
```bash
# KDE (bazzite-ally)
rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck:stable
# Gnome (bazzite-ally-gnome)
rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck-gnome:stable
```

We kept the old Ally image due to potential user demand for the changes there. However, we might discontinue it sooner because of this.

**Comment by SuperSirLink** [comment]
> If any of you are on the Ally image, it is recommended to switch to the Deck image using one of the following (depending on your Desktop Environment):
> 
> ```shell
> # KDE (bazzite-ally)
> rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck:stable
> # Gnome (bazzite-ally-gnome)
> rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck-gnome:stable
> ```
> 
> We kept the old Ally image due to potential user demand for the changes there. However, we might discontinue it sooner because of this.

How do we know which image we are on? I just installed it this week, am I good?

**Comment by us3rnam3d1** [comment]
Bumping this

installed bazzite somewhere around the end of June, so it’s a June build, no dual boot. 

Decided to reinstall windows last week. Rainbow RGB is broken. Before reinstalling, I left the HHD setting to rainbow. Is there any update on the issue? 

It’s the same for me, all options except rainbow are working. 

Rainbow is also working, but in aura sync mode.

**Comment by us3rnam3d1** [comment]
Hi

thanks for the swift reply!

I’m pretty confident it’s the ally image, I downloaded it from the main page and selected ally. It was the only first and only Linux install on the Ally. 

I’m running the latest bios and MCU firmware. Not sure if I can provide anything that can be of help to you guys, as my Ally is running windows exclusively now, and I didn’t dual boot in the first place. 

If I can do anything from within windows that can help you, let me know 

br

Deyan

**Comment by antheas** [comment]
Hi Deyan, seems like one of the Ally X units will be getting the -ally image treatment sooner than later then

Should be easy to fix after we identify the root cause

Of course, we will make our findings available to Asus and try to provide a windows workaround as well once a solution is found.

I do not think you can help much from Windows though. So we'd appreciate some (more) patience.

Thanks for understanding.

**Comment by antheas** [comment]
an update for all of you. We have received the following:
https://universal-blue.discourse.group/t/rainbow-rgb-not-working-after-reinstalling-windows/3487/3

If any of you are up for testing the fix that would be great. I am currently archiving the image, so do not worry about it expiring.

I will also analyze the package versions in it and 40-20240427 and delve deeper into this to isolate the solution if it does indeed work.

I was always aware of the reddit post, but I never realized they were talking about rebasing to the ally image.

**Comment by SuperSirLink** [comment]
I would be happy to test.  If we clone to another drive to test, fix the RGB, then go back to the original drive, would that be worth the effort?  Or would RGB just break again?

**Comment by antheas** [comment]
Yes, -deck is fixed. Please don't use the -ally image on the Ally. We will be removing it soon.

As soon as I diff the images and find out what caused it the latest bazzite will also fix the LEDs so you won't need to rebase

**Comment by antheas** [comment]
Sorry for the late response. -deck will not break them yes. Do not use -ally.

**Comment by Mia-Sophia** [comment]
> an update for all of you. We have received the following: https://universal-blue.discourse.group/t/rainbow-rgb-not-working-after-reinstalling-windows/3487/3
> 
> If any of you are up for testing the fix that would be great. I am currently archiving the image, so do not worry about it expiring.
> 
> I will also analyze the package versions in it and 40-20240427 and delve deeper into this to isolate the solution if it does indeed work.
> 
> I was always aware of the reddit post, but I never realized they were talking about rebasing to the ally image.
> 
> EDIT: The image is too old, so your installation might break. But your RGB might work again!

i tried this and it did fix my issue

**Comment by SuperSirLink** [comment]
What are the steps to test?  I can also try tonight.

**Comment by Mia-Sophia** [comment]
> What are the steps to test? I can also try tonight.
installed Fedora Kinoite 40 iso
then rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-ally:39-20240406
and when it came up like the guide said the led was red  and i returned to windows
and it worked

**Comment by ElvisChen1986** [comment]
**rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-ally:39-20240406**  solved the issue in my rog ally.
**40-20240427** does not work

**Comment by Evilexium** [comment]
> an update for all of you. We have received the following: https://universal-blue.discourse.group/t/rainbow-rgb-not-working-after-reinstalling-windows/3487/3
> 
> If any of you are up for testing the fix that would be great. I am currently archiving the image, so do not worry about it expiring.
> 
> I will also analyze the package versions in it and 40-20240427 and delve deeper into this to isolate the solution if it does indeed work.
> 
> I was always aware of the reddit post, but I never realized they were talking about rebasing to the ally image.
> 
> EDIT: The image is too old, so your installation might break. But your RGB might work again!

Yes it works , all good now finaly . But in fact this fix is what i allready mentioned weeks and weeks ago , but no one acted to it from bazzite Devs. I told them to fix the Keys problem so we can downgrade back to the 39 20240406 but they didnt react to that. Well now it seems to work the Rebase Rollback on Bazzite.

Now its best experience ever with CachyOS + HHD , and the fixed RGB Spiral Rainbow. All works perfectly :) even the Sleep Functions with the new kernels from cachyos. Thank you all

**Comment by antheas** [comment]
We did act on it, but you never specified it was the ally image. So we only tested the deck one

**Comment by SuperSirLink** [comment]
hmm, unless I did something wrong or my root issue is something else, this didn't work for me

**Comment by antheas** [comment]
Mind the fact this is a general Linux issue and not particular to Bazzite.

This means that the only image known to not cause it right now is bazzite-deck 

How did you check your issue was solved

**Comment by SuperSirLink** [comment]
I booted back into Windows, opened AC, and switched the leds back to rainbow. But they are still black.  

My trigger that broke it was also different. I followed the instructions on ASUS-Linux.org for Fedora workstation.  I was trying to install the Nvidia drivers and asusctl / supgfxctl when I lost RGB.

**Comment by antheas** [comment]
Guess what the Ally image and the steps you followed have in common :)

Do your LEDs not work at all? If yes, I have a command you can run to fix them.

**Comment by SuperSirLink** [comment]
What? :). Not sure if it matters, but I was running Nobara40 when I ran the commands.

Yeah, all the other modes work in Bazzite and in Windows, only the Spiral/Rainbow is not working in either.

**Comment by antheas** [comment]
asus-linux stuff

I had a command in case your LEDs did not work at all. We are still trying to figure out what caused the rainbow mode one.

In any case, seems like it is related to the 6 version of asus-linux and asusctl software family. And that running 5.0.10 fixes it. That software seems to be auto-enabling itself when you boot into the ally image. If not, forcing it open might help.

Between 6.0.0 and 5.0.10 there are too many changes for me to be able to pinpoint what caused the issue without a device. With a device, I would be able to sniff the packets. That will happen later this month.

Or sooner, if one of you wants to volunteer.

**Comment by antheas** [comment]
Yes, rebooting straight into windows or bazzite should work. Rebooting somewhere else inbetween no guarantees.

> how would I install that version?
Bazzite-ally 39 has this version. If you want to test in another distro you would have to repackage it by finding the package file and then install it...

**Comment by SuperSirLink** [comment]
Okay and if my "normal" Bazzite 40 install was done after the ally image was pulled, that should be good too?
rpm-ostree status will let me verify which I am running?

I am trying again to rebase from Fedora 40 to Bazzite 39, the LEDs came on red this time as it is booting and completing the install.  Not sure I saw that before.

**Comment by antheas** [comment]
> Okay and if my "normal" Bazzite 40 install was done after the ally image was pulled, that should be good too?

The deck image never had this problem. It does not matter how/when/where you installed, as long as you are in the deck image you will not have this issue.

**Comment by SuperSirLink** [comment]
Wohoo!  Worked on my second attempt!  I have Rainbow/Spiral back.  Thanks!

**Comment by KyleGospo** [comment]
We notified the asusctl developers of the problem and they're working on a fix now as well. Should have commands and a way to resolve this without rebasing soon.

**Comment by antheas** [comment]
I'm preparing a cross platform executable that should be able to fix this, if the asusctl developer's suspicion of the cause is correct

It will be available in a few hours and you will be able to run it on Linux and Windows

**Comment by helloman37** [comment]
> I'm preparing a cross platform executable that should be able to fix this, if the asusctl developer's suspicion of the cause is correct
> 
> It will be available in a few hours and you will be able to run it on Linux and Windows

If a solution is not found, I still will push my modded version. I can almost guarantee it's within the many modifications that was made to the source code of fedora that toys with the RGB lighting. Revert back to that image that had been discussed, build from there. The other shady part is the options within fedora that is modified is options to prevent users from doing as they wish. Such as rebase. Why lock it down so much. It looks rather shady to me. This up on toying with certain things causes freelancers such as the collaborative members to loose all credidation. 

Not being crude, it is just the truth. Such things that destroy something such as what people work hard for to buy causes a modded distro to loose all credit and respect. So, my advice instead of waiting months on end when the problem is being told to you, is to fix it.

Again, just basing the true hard facts. And if this new script fails such as the previous I will push my own fix.

**Comment by antheas** [comment]
Hi,

First of you are right. Waiting for months for a fix is not acceptable. We have put multiple guidelines in place to make sure this does not happen again. This included PURGING the whole software suite that caused it when running on the Ally.

This bug has not been a problem on Bazzite since June, when we deprecated the -ally image for running on the Ally. There are thousands of Ally and Ally X owners with perfectly running RGB currently.  This thread is still open for existing Ally owners that were affected. 

**All Ally X owners on Bazzite have working RGB**

The images with the offending software are still left for the Asus laptop owners that may want to use them. If we get further pushback, we may choose to retire the images completely.

> I can almost guarantee it's within the many modifications that was made to the source code of fedora that toys with the RGB lighting.

You are right. We have found and purged the source of the issue. As part of our diagnosing, we also went in and removed RGB code that runs on the Ally and is part of fedora.

We now believe we have isolated the issue and are ready to push a fix for existing units.

> Revert back to that image that had been discussed, build from there. 

The only reason that image fixes the leds is that it is running a doubly broken version of the software that broke them fixes them. As you understand, this is in no way an acceptable solution.

**Comment by antheas** [comment]
The initial version of the fix can be found below.
https://github.com/hhd-dev/ally-fix

It has not been verified to work.

Later today the readme will be updated explaining the source of the issue and the fix, and once verified to work, the fix will be packaged for Windows.

**Comment by antheas** [comment]
Has to be uploaded somewhere before it's tested

Hope that makes sense, we do not live in the same house after all

The command in the fixer has been tested and is known not to cause any issues. What's being tested is the packaging itself working and whether it fixes the issue

Let me share your sentiment though. Due to courier whoes I won't have access to an ally for the next week or so. So you can either wait for one of our contributors to help or help with fixing the issue.

If you do want to help, please open an issue on the fix issue tracker, as this thread is long enough and too many people are notified at this point.

**Comment by helloman37** [comment]
> Has to be uploaded somewhere before it's tested
> 
> Hope that makes sense, we do not live in the same house after all
> 
> The command in the fixer has been tested and is known not to cause any issues. What's being tested is the packaging itself working and whether it fixes the issue
> 
> Let me share your sentiment though. Due to courier whoes I won't have access to an ally for the next week or so. So you can either wait for one of our contributors to help or help with fixing the issue.
> 
> If you do want to help, please open an issue on the fix issue tracker, as this thread is long enough and too many people are notified at this point.
> 
> EDIT: And yes, since you edited your comment, I do treat you as my consumers. Which is why I spent over a month diagnosing an issue I did not cause and providing the fix for it.

Very good. Now we are getting somewhere. Just know in a business world things go bad for investors, developers etc.... when things like this happen. 

In turn, if it were me I would host the code on my site not open till proven fixed. Just my own way of thinking. But I am also trying to protect you as well by making you seriously aware of this as you already are. The situations with this, by any distro is serious. That's why Linux is open source. Which is why your distros should be as well. Refer to YouTube link below.

However, as a consumer there is a demand. And why rebase is nulled out is beyond me. 

This is a lot that needs to be resolved. 

https://youtu.be/AQBSA69MWAg?si=_mg48eF2Ul1y40iR 

^^^^^^ What he speaks on is serious. ^^^^^^

**Comment by antheas** [comment]
Hi, let us move the discussion on the ally-fix issue tracker. You can rant there as much as you want, and people are free to go there with their popcorn 🍿. You may even edit your previous comment to point to the issue as well, to make it easier for them to find.

However if you post another comment here you will be muted.

That being said yes, I will take you up on your offer. If this breaks your Ally ill send you my Ally X unit.

**Comment by KyleGospo** [comment]
To be 100% clear, this bug is:

1. In software we don't write that is shipped by default in other distros.
2. Not damaging to hardware and reversible.
3. In the progress of being fixed in the software at fault
4. Has automatically applied fixes in development by the Bazzite team for affected users.
5. Can be recovered from now by running an older Bazzite build or an older version of asusctl.

There is little more we can do here. Even getting to the point of being able to point the finger at another project took time and debugging to find. I ask that you adhere to our code of conduct at all times in this issue tracker.

**Comment by helloman37** [comment]
> Hi, let us move the discussion on the ally-fix issue tracker. You can rant there as much as you want, and people are free to go there with their popcorn 🍿. You may even edit your previous comment to point to the issue as well, to make it easier for them to find.
> 
> However if you post another comment here you will be muted.
> 
> That being said yes, I will take you up on your offer. If this breaks your Ally ill send you my Ally X unit.

Lol 🤣 y'all are fun. But I don't believe you.

**Comment by helloman37** [comment]
> Hi, let us move the discussion on the ally-fix issue tracker. You can rant there as much as you want, and people are free to go there with their popcorn 🍿. You may even edit your previous comment to point to the issue as well, to make it easier for them to find.
> 
> However if you post another comment here you will be muted.
> 
> That being said yes, I will take you up on your offer. If this breaks your Ally ill send you my Ally X unit.

When should I expect my replacement? I tried it, my Ally doesn't even turn on anymore. It was fully charged before I tested.

**Comment by KyleGospo** [comment]
> Hello Bazzite team and community :D 
> So, as a fresh person that just found out the existence of the distro and want to try it out, is it safe to assume and the current release version is "safe to download" (on my Ally X)?
> 
> P.s. Just 2h ago or so, the website had a warning, but now does not :O 
> Great job :O 

Yes, this issue is only present in builds from a couple months ago when we still used Asusctl to control RGB instead of HHD. If you're not currently affected you can expect to continue to not be affected.

**Comment by us3rnam3d1** [comment]
Ran the fix on windows, doesn’t work. Cmd window pops up very briefly and then disappears.

**Comment by us3rnam3d1** [comment]
> > Ran the fix on windows, doesn’t work. Cmd window pops up very briefly and then disappears.
> 
> Quick check, did you run that as administrator? It needs permissions to send the command to the RGB controller.

Hi, yes. First time I didn’t run it as admin, second time I tried. Same issue :(

**Comment by KyleGospo** [comment]
> > > Ran the fix on windows, doesn’t work. Cmd window pops up very briefly and then disappears.
> > 
> > Quick check, did you run that as administrator? It needs permissions to send the command to the RGB controller.
> 
> Hi, yes. First time I didn’t run it as admin, second time I tried. Same issue :(

We're looking into it now and will get back to you shortly.

**Comment by antheas** [comment]
Hi @us3rnam3d1, the .exe file opens on my computer but we know it wouldn't be perfect the first time. There is a good chance a dependency is missing

If you want to help, run the exe using PowerShell or a cmd shell and give us the output

The window is meant to stay open

**Comment by us3rnam3d1** [comment]
> Hi @us3rnam3d1, the .exe file opens on my computer but we know it wouldn't be perfect the first time. There is a good chance a dependency is missing
> 
> If you want to help, run the exe using PowerShell or a cmd shell and give us the output
> 
> The window is meant to stay open
> 
> You may also opt to run the python file which will definitely work

Lemme give it a shot and I’ll get back to you, thanks

**Comment by us3rnam3d1** [comment]
> Hi @us3rnam3d1, the .exe file opens on my computer but we know it wouldn't be perfect the first time. There is a good chance a dependency is missing
> 
> If you want to help, run the exe using PowerShell or a cmd shell and give us the output
> 
> The window is meant to stay open
> 
> You may also opt to run the python file which will definitely work

Tried running ally-fix.py from Powershell, nothing happened. Said “press any key to continue” and that was it.

trying to run the exe from powershell just opens a new cmd and it dissappears right after :(

**Comment by antheas** [comment]
Seems like @HikariKnight bundled the wrong dll then unfortunately and it crashes when it tries to load the file.

I forgot to put a print statement there

We will fix it soon and post an update

**Comment by HikariKnight** [comment]
It is the only dll from libusb so not sure what else is needed 🤔

**Comment by antheas** [comment]
I fixed the logging issue. The script will no longer crash and not show anything on windows.

Also, the reason the script said press any key to exit was that libhidapi was not installed. The error was missing so I also added it as well.

However, I still do not know why the .exe did not run. Perhaps it needs a usagepage change. We will only know if we get the error from the exe that can be found below:
https://github.com/hhd-dev/ally-fix/releases/tag/v1.1.0

**Comment by KyleGospo** [comment]
> > Hi @us3rnam3d1, the .exe file opens on my computer but we know it wouldn't be perfect the first time. There is a good chance a dependency is missing
> > If you want to help, run the exe using PowerShell or a cmd shell and give us the output
> > The window is meant to stay open
> > You may also opt to run the python file which will definitely work
> 
> Tried running ally-fix.py from Powershell, nothing happened. Said “press any key to continue” and that was it.
> 
> trying to run the exe from powershell just opens a new cmd and it dissappears right after :(

Another tester confirmed this version is working on Windows:
https://github.com/hhd-dev/ally-fix/releases/tag/v1.2.0

Let us know if you agree and we can mark this as the stable release.

**Comment by us3rnam3d1** [comment]
> > > Hi @us3rnam3d1, the .exe file opens on my computer but we know it wouldn't be perfect the first time. There is a good chance a dependency is missing
> > > If you want to help, run the exe using PowerShell or a cmd shell and give us the output
> > > The window is meant to stay open
> > > You may also opt to run the python file which will definitely work
> > 
> > 
> > Tried running ally-fix.py from Powershell, nothing happened. Said “press any key to continue” and that was it.
> > trying to run the exe from powershell just opens a new cmd and it dissappears right after :(
> 
> Another tester confirmed this version is working on Windows: https://github.com/hhd-dev/ally-fix/releases/tag/v1.2.0
> 
> Let us know if you agree and we can mark this as the stable release.

Hi

it works! I used the exe on windows. Great work, thank you!!!

**Comment by s0bolh02** [comment]
> > > Hi @us3rnam3d1, the .exe file opens on my computer but we know it wouldn't be perfect the first time. There is a good chance a dependency is missing
> > > If you want to help, run the exe using PowerShell or a cmd shell and give us the output
> > > The window is meant to stay open
> > > You may also opt to run the python file which will definitely work
> > 
> > 
> > Tried running ally-fix.py from Powershell, nothing happened. Said “press any key to continue” and that was it.
> > trying to run the exe from powershell just opens a new cmd and it dissappears right after :(
> 
> Another tester confirmed this version is working on Windows: https://github.com/hhd-dev/ally-fix/releases/tag/v1.2.0
> 
> Let us know if you agree and we can mark this as the stable release.

Just ran the .exe myself and it worked successfully, my RGB is 100% working like it used to.

**Comment by KyleGospo** [comment]
Closing as completed ! Issue will remain open for further support w/ this utility and will remain pinned.
