### ISSUE TITLE
OneXPlayer1 AMD's screen doesn't wake up after suspend

### ISSUE THREAD

**Issue by kalzEOS** [ublue-os/bazzite#2081]
### Describe the bug

The screen stays black, I can still hear the UI sounds when I move around and click on things but the screen is off. When I press the power button on the back once or twice, it takes a second to wake up then starts flashing dimming and brightening then shuts off, sometimes it works, others it goes back to black and I'd need to hold down the power button to turn it off and on

### What did you expect to happen?

Normal screen after suspend

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:011580d0843e0c6ffbd23ec56eadcfb6bf564020b9b28f2aacf612e796ea178b
                  Version: 41.20250106.1 (2025-01-06T14:19:15Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:1c4c029309a887eb561e346ed469b72ed75c59451bd9eb0a873b0b507ec71f98
                  Version: 41.20241230.1 (2024-12-30T06:48:54Z)
```

### Hardware

Operating System: Bazzite 41
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.8-201.bazzite.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700U with Radeon Graphics
Memory: 12.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: ONE-NETBOOK TECHNOLOGY CO., LTD.
Product Name: ONE XPLAYER

**Comment by aurelios69** [comment]
I'm having the exact same issue. With the same Onexplayer AMD

**Comment by KarkanAlzwayed** [comment]
> I'm having the exact same issue. With the same Onexplayer AMD

I have actually installed windows on it for now. It was just unusable at all.

**Comment by aurelios69** [comment]
Too bad. I just use bazzite on my legion go and ally z1e. I'm also installing windows. Hopefully this will be fixed. This doesn't happen with nobara, just with bazzite.

**Comment by KarkanAlzwayed** [comment]
> Too bad. I just use bazzite on my legion go and ally z1e. I'm also installing windows. Hopefully this will be fixed. This doesn't happen with nobara, just with bazzite.

I haven't messed with Nobara on handheld. I didn't know if it supported the things that I care about like the "turbo" button, TDP control and fan....etc. Does it? If it does, I'll use it. Windows sucks ass on handhelds.

**Comment by aurelios69** [comment]
I've just installed it last night. Didn't had much time to finish things. I've also installed handheld daemon, the side buttons are working. The wifi seems to be working properly too. On bazzite it usually was disabled, had to restart the unit several times for it to work.

**Comment by kdog31** [comment]
Sounds like a duplicate of #2054, as per my comment there, the issue is upstream with the AMDGPU driver. It has been resolved in a new kernel version, just need to wait for it to be included in fedora. Should be soon the new kernel was released late December.

**Comment by aurelios69** [comment]
That's great. My onexplayer does exactly that. With the screen flashing

**Comment by KarkanAlzwayed** [comment]
> I've just installed it last night. Didn't had much time to finish things. I've also installed handheld daemon, the side buttons are working. The wifi seems to be working properly too. On bazzite it usually was disabled, had to restart the unit several times for it to work.
> 
> By the way, your unit doesn't randomly turns off while using bazzite? Mostly when the os finishes loading right before the menu appears.

- First, what's handheld daemon? Is that to make the turbo button, keyboard button, side button and steam menu button work? 
- I had the same issue with wifi on bazzite. It was very irritating. It happens every time after the device suspended and I woke it to play something. No wifi no matter what I did and I had to reboot the machine, otherwise no Internet for me. I've filed another bug for it on here and no one has looked into it yet. 
- Yes, my unit flashed like crazy and it turned off while I'm navigating the system. It happens, again, after I wake it up from suspend. It looks like the OS is not recognizing the internal screen, and doesn't keep it awake. So, it flashes a couple of times then turns off and I have to force the unit off. Doesn't happen when connected to a monitor.

**Comment by KarkanAlzwayed** [comment]
> Sounds like a duplicate of [#2054](https://github.com/ublue-os/bazzite/issues/2054), as per my comment there, the issue is upstream with the AMDGPU driver. It has been resolved in a new kernel version, just need to wait for it to be included in fedora. Should be soon the new kernel was released late December.

I don't run Fedora on any of my machines, so I wouldn't know. Could you please just ping me on here to let me know when it's released? I really want to get rid of windows on my unit. It's driving me insane. Thank you.

**Comment by kdog31** [comment]
> > Sounds like a duplicate of [#2054](https://github.com/ublue-os/bazzite/issues/2054), as per my comment there, the issue is upstream with the AMDGPU driver. It has been resolved in a new kernel version, just need to wait for it to be included in fedora. Should be soon the new kernel was released late December.
> 
> I don't run Fedora on any of my machines, so I wouldn't know. Could you please just ping me on here to let me know when it's released? I really want to get rid of windows on my unit. It's driving me insane. Thank you.

It's good to track these issues yourself instead of relying on others pinging you (I could be on holidays rn and you'd never know),it's worth mentioning I'm not one of the bazzite Devs, just saw your issue and knew what it was to steer you in the right direction, and bring some hope.

But I digress, Kernel 6.12.10-200 is now included in Fedora, the issue is resolved as of 6.12.9-200.

6.12.10-202 is included in bazzite 41.20250124 (released overnight for me) your issue should be resolved with the new kernel.

**Comment by KarkanAlzwayed** [comment]
> > > Sounds like a duplicate of [#2054](https://github.com/ublue-os/bazzite/issues/2054), as per my comment there, the issue is upstream with the AMDGPU driver. It has been resolved in a new kernel version, just need to wait for it to be included in fedora. Should be soon the new kernel was released late December.
> > 
> > 
> > I don't run Fedora on any of my machines, so I wouldn't know. Could you please just ping me on here to let me know when it's released? I really want to get rid of windows on my unit. It's driving me insane. Thank you.
> 
> It's good to track these issues yourself instead of relying on others pinging you (I could be on holidays rn and you'd never know),it's worth mentioning I'm not one of the bazzite Devs, just saw your issue and knew what it was to steer you in the right direction, and bring some hope.
> 
> But I digress, Kernel 6.12.10-200 is now included in Fedora, the issue is resolved as of 6.12.9-200.
> 
> 6.12.10-202 is included in bazzite 41.20250124 (released overnight for me) your issue should be resolved with the new kernel.

No need for the lecture, you could have just ignored me and called it a day. Thanks for confirmation the kernel version anyway.

**Comment by kdog31** [comment]
> > > > Sounds like a duplicate of [#2054](https://github.com/ublue-os/bazzite/issues/2054), as per my comment there, the issue is upstream with the AMDGPU driver. It has been resolved in a new kernel version, just need to wait for it to be included in fedora. Should be soon the new kernel was released late December.
> > > 
> > > 
> > > I don't run Fedora on any of my machines, so I wouldn't know. Could you please just ping me on here to let me know when it's released? I really want to get rid of windows on my unit. It's driving me insane. Thank you.
> > 
> > 
> > It's good to track these issues yourself instead of relying on others pinging you (I could be on holidays rn and you'd never know),it's worth mentioning I'm not one of the bazzite Devs, just saw your issue and knew what it was to steer you in the right direction, and bring some hope.
> > But I digress, Kernel 6.12.10-200 is now included in Fedora, the issue is resolved as of 6.12.9-200.
> > 6.12.10-202 is included in bazzite 41.20250124 (released overnight for me) your issue should be resolved with the new kernel.
> 
> No need for the lecture, you could have just ignored me and called it a day. Thanks for confirmation the kernel version anyway.

Not trying to lecture, I apologise if it came off that way. It is just good general practice to keep up with the issues you face yourself as others will almost certainly have different hardware etc.

anyways be sure to mark this issue as fixed if the new kernel does in fact fix your issue.

**Comment by KarkanAlzwayed** [comment]
> > > > > Sounds like a duplicate of [#2054](https://github.com/ublue-os/bazzite/issues/2054), as per my comment there, the issue is upstream with the AMDGPU driver. It has been resolved in a new kernel version, just need to wait for it to be included in fedora. Should be soon the new kernel was released late December.
> > > > 
> > > > 
> > > > I don't run Fedora on any of my machines, so I wouldn't know. Could you please just ping me on here to let me know when it's released? I really want to get rid of windows on my unit. It's driving me insane. Thank you.
> > > 
> > > 
> > > It's good to track these issues yourself instead of relying on others pinging you (I could be on holidays rn and you'd never know),it's worth mentioning I'm not one of the bazzite Devs, just saw your issue and knew what it was to steer you in the right direction, and bring some hope.
> > > But I digress, Kernel 6.12.10-200 is now included in Fedora, the issue is resolved as of 6.12.9-200.
> > > 6.12.10-202 is included in bazzite 41.20250124 (released overnight for me) your issue should be resolved with the new kernel.
> > 
> > 
> > No need for the lecture, you could have just ignored me and called it a day. Thanks for confirmation the kernel version anyway.
> 
> Not trying to lecture, I apologise if it came off that way. It is just good general practice to keep up with the issues you face yourself as others will almost certainly have different hardware etc.
> 
> anyways be sure to mark this issue as fixed if the new kernel does in fact fix your issue.

No worries. Issue is still present along with the wifi one, too. Brand new install, too. Keeping this open.

**Comment by CheckYourFax** [comment]
Does this issue still exist on the latest version of Bazzite?

**Comment by CheckYourFax** [comment]
That's up to you. I'll mark the issue as stale, and you can update the ticket if the issue is still present.

**Comment by kalzEOS** [comment]
> That's up to you. I'll mark the issue as stale, and you can update the ticket if the issue is still present.

Ok, I am downloading the iso. I will install and test. I will report back after. I still have two other reports for two other issues that I will follow up on, too

**Comment by kalzEOS** [comment]
Ok @CheckYourFax device just doesn't sleep or even shutdown anymore. Whether I use the power button or the software button from the steam menu, it just stays up. I can tell from the fan, it keeps spinning as if the machine is awake. The screen stays dark for about 30 - 40 seconds then the device wakes up again. Wifi still dies after the "suspend". When shutting down, the screen just goes black, but the power light is still on and the fan still keeps spinning. Screen never wakes up anymore, and I'd have to kill the device by holding the power button

**Comment by CheckYourFax** [comment]
`journalctl -b 0 > "$(xdg-user-dir DESKTOP)/systemlog.txt"`

Run this in terminal and upload the .txt that generates on your desktop here.

**Comment by kalzEOS** [comment]
> Ok [@CheckYourFax](https://github.com/CheckYourFax) device just doesn't sleep or even shutdown anymore. Whether I use the power button or the software button from the steam menu, it just stays up. I can tell from the fan, it keeps spinning as if the machine is awake. The screen stays dark for about 30 - 40 seconds then the device wakes up again. Wifi still dies after the "suspend". When shutting down, the screen just goes black, but the power light is still on and the fan still keeps spinning. Screen never wakes up anymore, and I'd have to kill the device by holding the power button

[systemlog.txt](https://github.com/user-attachments/files/19983248/systemlog.txt)

**Comment by CheckYourFax** [comment]
@antheas

**Comment by antheas** [comment]
It happens with some devices. Especially if the screen is OLED or a bit weird. Has to do with the display.

**Comment by antheas** [comment]
We need a device to test unfortunately

**Comment by kalzEOS** [comment]
I don't have an oled screen. And if my device works, I don't mind using it to test. Here are its info if that helps
Operating System: Bazzite 41
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.9-103.bazzite.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700U with Radeon Graphics
Memory: 12.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: ONE-NETBOOK TECHNOLOGY CO., LTD.
Product Name: ONE XPLAYER

**Comment by antheas** [comment]
Try bazzite f42. We bumped gamescope maybe it helps

**Comment by kalzEOS** [comment]
Is that beta?

**Comment by antheas** [comment]
You might need to update from desktop. There was an issue in your version

**Comment by kalzEOS** [comment]
Like update the whole system to f42? I don't know how to update

**Comment by kalzEOS** [comment]
Do I use `rpm-ostree rebase`?

**Comment by antheas** [comment]
There's a desktop updater. Otherwise `sudo rpm-ostree update`

**Comment by kalzEOS** [comment]
Just updated to f42. Suspend works now, but shutdown doesn't. Device goes into this loop of fan spinning speeds fluctuation, where it ramps up for a second then slows down as if it's trying to do something. WiFi dead after suspend issue is still there (I'm going to try to see if there is something in the BIOS for the wifi that I can get it fixed with), I don't know.

**Comment by antheas** [comment]
Wifi issue is also known for your CPU generation. It happens on the Ayaneo 1S too I think

**Comment by kalzEOS** [comment]
No fix for it? It was happening on my friend's ROG Ally x, and he was able to fix it by disabling hibernation on Windows since he dualbooted. I had no hibernate on Windows to disable before installing Bazzite. Also, I didn't find anything for it in the BIOS. I did find that "fast boot" was enabled and disabled it. (I think) the shutdown issue is now fixed. It's pretty annoying. I have to reboot my device every time I wake it up so I can have internet

**Comment by antheas** [comment]
The hibernation thing is unrelated unfortunately

**Comment by kalzEOS** [comment]
It is working very well now (compared to a couple of months ago). Only the wifi issue. I can put up with that

**Comment by DCKcode** [comment]
#2974 potentially fixes this issue, but I don't have OneXPlayer 1 to test with.

You can test whether it works by temporarily rebasing to the image from my own repository: `rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/DCKcode/bazzite:stable`

**Comment by kalzEOS** [comment]
> [#2974](https://github.com/ublue-os/bazzite/pull/2974) potentially fixes this issue, but I don't have OneXPlayer 1 to test with.
> 
> You can test whether it works by temporarily rebasing to the image from my own repository: `rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/DCKcode/bazzite:stable`

I don't usually do this, but I went out on a limb and rebased. I can't test it on game mode, because it completely breaks game mode. After rebasing and rebooting, it takes me straight into the desktop mode and I have to enter my password to log in. I logged in fine, switched to game mode, and it was stuck at a dim screen, but it never goes to game mode. Essentially, game mode is gone. I have read the comment on your PR and you didn't mention any of that. Maybe something to add in the comment as a disclaimer or a warning for those who want to test. As for it working, it does only on hardwired, not Wi-Fi. Wi-Fi is still gone after the machine wakes from suspend. Unplugged the Ethernet cable to see if the wifi is there, it is not, then the machine just froze completely and nothing worked but Ctrl+alt+del then I restarted it. It never started again until I forced shut it off and then start again. Again, booted into desktop mode directly. Suspended it again and woke it up. Had to log in like a normal desktop. No wifi. Pulled the drop down menu where I can toggle the wifi on and off. Every time I toggle it, it freezes the whole system for around 20 seconds or so then it is responsive. Still no wifi until I reboot. Plugged in the Ethernet, and that works. At least that works now, it didn't use to work before. 
Side note, running this `rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/DCKcode/bazzite:stable` threw an error complaining about cap letters in DCKcode. Made it all small letters for it to run. Let me know if there is any other test you want me to run. For now, I want to revert back to the original Bazzite so I can get to my games. lol

**Comment by DCKcode** [comment]
That's very interesting and unexpected, as there's no changes from upstream Bazzite other than a minor fix for the wifi. The same image runs fine on my Ayaneo Air, just like mainline Bazzite. There might be another issue with your setup that causes problems.

Unless someone else reports otherwise (@JNer1 perhaps?) I'll revert the OneXPlayer fix from #2974 to avoid any issues.

**Comment by JNer1** [comment]
@DCKcode I can confirm the issue experienced by @kalzEOS when trying `rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/DCKcode/bazzite:stable`. It breaks Steam Gaming Mode and also doesn't fix the WiFi issue, unlike the manual workaround you described in #2134. 

Perhaps because it is using bazzite:stable and not bazzite-deck:stable? I had to rebase back to `rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck:stable` to get my OneXPlayer 1 back to working condition and re-enabling the manual workaround for the WiFi.

**Comment by DCKcode** [comment]
Oh I realize the mistake, I gave the wrong instruction! 

The actual fixed image is obtained by `rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/dckcode/bazzite-deck:stable`. You're right you need the deck image for this to work. I expect that one to work on the OneXplayer. Sorry about that.

**Comment by kalzEOS** [comment]
> Oh I realize the mistake, I gave the wrong instruction!
> 
> The actual fixed image is obtained by `rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/dckcode/bazzite-deck:stable`. You're right you need the deck image for this to work. I expect that one to work on the OneXplayer. Sorry about that.

No problem. I didn't rebase, I just created the systemd service you have suggested [here](https://github.com/ublue-os/bazzite/issues/2134#issuecomment-3090683978), and the device now works fine. Sleeps and wakes up no problem, and Wi-Fi is back on as well. Also, thank you for this. Now my device is useful again after it's been sitting around not being used at all. You saved it :)

**Comment by DCKcode** [comment]
Good to hear! Any chance I can get you to test my image again?

The fix is two parts: one - the actual fix. Two - detecting Bazzite is running on a OneXPlayer and automatically applying the fix. I want to make sure I also got the second part right, and I don't have a OneXPlayer myself to test.

That way we can help other people who have their OneXPlayer gathering dust or stuck on Windows too.

**Comment by kalzEOS** [comment]
> Good to hear! Any chance I can get you to test my image again?
> 
> The fix is two parts: one - the actual fix. Two - detecting Bazzite is running on a OneXPlayer and automatically applying the fix. I want to make sure I also got the second part right, and I don't have a OneXPlayer myself to test.
> 
> That way we can help other people who have their OneXPlayer gathering dust or stuck on Windows too.

Of course. Send it as long as you know it won't make me reinstall everything. Lol

**Comment by DCKcode** [comment]
You should be able to test it by:

```bash
 # disable workaround you added to test the one in the image
systemctl disable mt7921e-sleep-workaround
rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/dckcode/bazzite-deck:stable
```
After a reboot you should get the Bazzite deck experience with Steam UI and still have working sleep.

After confirming it works. you can go back to stable as follows:

```bash
systemctl enable mt7921e-sleep-workaround
rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
```

**Comment by kalzEOS** [comment]
> You should be able to test it by:
> 
>  # disable workaround you added to test the one in the image
> systemctl disable mt7921e-sleep-workaround
> rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/dckcode/bazzite-deck:stable
> 
> After a reboot you should get the Bazzite deck experience with Steam UI and still have working sleep.
> 
> After confirming it works. you can go back to stable as follows:
> 
> systemctl enable mt7921e-sleep-workaround
> rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable

So that killed the wifi permanently. Even after a reboot, the wifi is dead completely. Even after running ``systemctl enable mt7921e-sleep-workaround`` then rebooting. Gone forever. lol. Now I have to see if an Ethernet will give me my Internet back so I can revert to official bazzite, otherwise, I'll have to reinstall

**Comment by DCKcode** [comment]
Oh my, that is really unexpected, sorry to be inadvertently causing these issues. Unless there's a specific issue with your device only, the OneXPlayer might have issues beyond that of the Ayaneo Air devices and I might have to give up on giving it an automatic fix.

What does the command `modprobe mt7921e` give you? That should reenable the wifi kernel module even with the service running. If not, does the output of `lspci` show you a wifi module in the first place?

**Comment by kalzEOS** [comment]
> Oh my, that is really unexpected, sorry to be inadvertently causing these issues. Unless there's a specific issue with your device only, the OneXPlayer might have issues beyond that of the Ayaneo Air devices and I might have to give up on giving it an automatic fix.
> 
> What does the command `modprobe mt7921e` give you? That should reenable the wifi kernel module even with the service running. If not, does the output of `lspci` show you a wifi module in the first place?

I personally think you should keep it at the PR level where you add the systemd service that actually works no issues. I think it would be a better fix for onexplayer owners and for you personally since you don't have the device. That systemd service works 100% for me and literally brought my device from the dead. I had that machine sitting in a drawer for months now, and now I pretty much use it every single day thanks to your fix.

**Comment by DCKcode** [comment]
I reverted the part that automatically applies the workaround on the OneXPlayer. Once merged though, you can enable it with one command.

**Comment by kalzEOS** [comment]
> I reverted the part that automatically applies the workaround on the OneXPlayer. Once merged though, you can enable it with one command.

So, I'll need to run the ``systemctl enable mt7921e-sleep-workaround`` after I rebase to your image? If so, what is the difference from just running the command on the default bazzite image. Am I understanding this whole thing wrong?

**Comment by DCKcode** [comment]
If you already have manually added the service in `/etc` like you do, no need to do anything as the workaround will be active and remain there across updates and new images.

Anyone else will need to run `systemctl enable --now kmod-sleep-workaround@mt7921e` once #2974 merges in.

**Comment by kalzEOS** [comment]
> If you already have manually added the service in `/etc` like you do, no need to do anything as the workaround will be active and remain there across updates and new images.
> 
> Anyone else will need to run `systemctl enable --now kmod-sleep-workaround@mt7921e` once [#2974](https://github.com/ublue-os/bazzite/pull/2974) merges in.

Makes sense, thanks. I checked the latest commit of your PR, and it looks like you removed the mention of the OneXPlayer from the list of affected devices fixed by this update. I want to help make that official. I know I'm slow to respond (two kids and a job lol), but I want to make this official so it can be merged into Bazzite.

**Comment by DCKcode** [comment]
No worries, appreciate the help! Though when you say "I want to help make that official" - what do you mean?

**Comment by kalzEOS** [comment]
> No worries, appreciate the help! Though when you say "I want to help make that official" - what do you mean?

I could be wrong, but looking at your latest commit, I see that the PR is officially for the Aya neo devices, but not onexplayer. It looks like the onexplayer was included as a device that is officially supported by this fix, but then you removed it and kept the Aya neo.

**Comment by DCKcode** [comment]
Right yeah, so [as I said](https://github.com/ublue-os/bazzite/issues/2081#issuecomment-3165609039) - I removed applying the workaround to the OneXPlayer 1 because it appears you were running into issues.

Given I don't have access to a OneXPlayer 1, that's really all I can do. If it doesn't work automatically, there's some device specific issues to debug. If the issues you encountered extend to all OneXPlayer 1 devices out there, someone with a device like that will have to figure out how to automatically apply the workaround and open a new PR.
