### ISSUE TITLE
Xbox Controller Unresponsive on Wake from Suspend (Bazzite)

### ISSUE THREAD

**Issue by Randy28CR** [ublue-os/bazzite#2367]
### Describe the bug

Hello team! After waking the system from sleep the Xbox controller successfully connects to the dongle but is unresponsive in Steam. Since usbreset is not included in the Bazzite image it's not a feasible workaround for Bazzite. To fix, the dongle needs to be unplugged but only after turning the controller off first. System reboot does not fix the issue.

### What did you expect to happen?

Repro Steps:

In Steam game mode via the controller put the system to sleep
Wake the system from sleep via the Xbox button (back into Steam game mode)

### Output of `rpm-ostree status`

```shell

```

### Hardware

Hardware/System:

Xbox Elite 2 (Latest Firmware) connected via the Xbox Wireless Adapter (Unknown Firmware).
Bazzite 41 (FROM Fedora Kinoite); Linux 6.13.5-100.bazzite.fc41.x86_64

### Extra information or context

Logs:

[dmesg](https://github.com/user-attachments/files/19054183/dmesg.log)
[boot](https://github.com/user-attachments/files/19054203/boot.log)
[lsusb](https://github.com/user-attachments/files/19054866/lsusb.log)
[modinfo](https://github.com/user-attachments/files/19054924/modinfo.log)

**Comment by SanelessOne** [comment]
I've had this issue for a while too. Other distros as well. I don't need to turn off my controller itself, but definitely have to unplug it and plug it back in

**Comment by Fmstrat** [comment]
Anyone find a workaround? Like resetting USB on wake?

**Comment by ArnauS197** [comment]
> Anyone find a workaround? Like resetting USB on wake?

It does not work, even with usbreset command.

**Comment by evrowe** [comment]
Same issue here with an Xbox Series controller and Xbox USB Wireless dongle; it used to persist until I would switch to my Windows partition and have to re-connect there but now it happens every time Bazzite suspends/resumes, and sometimes even just from powering the controller off and back on again. Would love to have this fixed as it's kind of a pain for using the controller at all.

**Comment by neomedved** [comment]
Same problem with Xbox Series controller and Xbox USB Wireless dongle. Unplugging the dongle without turning controller off helps though

**Comment by SanelessOne** [comment]
Mine actually magically started working right after trying like 7 different USB ports. Not sure if my MB treats it different than the rest but I haven't had an issue in a month

**Comment by ArnauS197** [comment]
In my case I just gave up and bought the 8bitdo Ultimate 2 (on Amazon theres a 10% coupon code) which works just perfect on Linux as far as I know.

**Comment by evrowe** [comment]
@ArnauS197 Same here, actually!  Works like a charm, no more of this nonsense.

Shouldn't be surprising knowing that Microsoft's dongle uses a proprietary protocol anyway.

**Comment by Fmstrat** [comment]
I mean, if you pair the Xbox controller with Bluetooth it works fine, too. Even the paddles on the Elite controller. The catch is input delay for if you play games where that matters.

**Comment by HunterAhlquist** [comment]
> I mean, if you pair the Xbox controller with Bluetooth it works fine, too. Even the paddles on the Elite controller. The catch is input delay for if you play games where that matters.

Also you wont be able to wake from sleep with the controller. Edit: or use the controller's headphone jack.

**Comment by andyschmid** [comment]
The current xone-kmod package appears to be using an old archive of the source when building. I'm having a hard time finding the exact commit being used.

I just pulled the latest tip of https://github.com/bazzite-org/xonedo (3ec5e6d5c6f88188f354b243a19035817d4088fc) and built the kmod locally, unloaded the packaged modules and loaded the latest version. I can confirm with current xonedo code the controller works after resuming from suspend.

The COPR build process is new to me, so I'm not quite sure why the latest commit is not being packaged. I will continue to investigate, but I am hoping the package maintainer can help address this issue.

**Comment by andyschmid** [comment]
The latest COPR build of the xone-kmod package is version 1000.0.0.git.1114.82438c9a-1 from Aug 28th, https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/build/9498342/

The xonedo source used is from https://github.com/bazzite-org/xonedo (874f3800321722ba42c3c0875b374df0fa9b4849), which is about 2 months behind.

**Comment by antheas** [comment]
> The latest COPR build of the xone-kmod package is version 1000.0.0.git.1114.82438c9a-1 from Aug 28th, https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/build/9498342/
> 
> The xonedo source used is from https://github.com/bazzite-org/xonedo (874f3800321722ba42c3c0875b374df0fa9b4849), which is about 2 months behind.

Not true.

Here is the version used that shipped on f43
https://github.com/bazzite-org/xonedo/tree/2c06de29e95bbe9beebb81924f4b7324f0eb6591

The akmods repository was dropped for bazzite as of f43

**Comment by antheas** [comment]
This bug should be fixed as of the latest version. If not, reopen.

Briefly during testing for f43 I added xoneneo, which caused a similar issue. But it is not present on the build that shipped

**Comment by andyschmid** [comment]
Thanks for the clarification @antheas, as I mentioned before I'm not too familiar with the build process but trying to help debug this issue.

**Comment by Fmstrat** [comment]
@andyschmid while it seems that wasn't the issue, Thank you for digging in. Oftentimes analysis like that can lead to a resolution. Keep on contributing where you can!

**Comment by HunterAhlquist** [comment]
I'm confused as to how to apply this fix, I tried every branch and the issue still happens.

**Comment by HunterAhlquist** [comment]
Perhaps there is a different issue because plugging in the dongle into the BIOS flashback USB port as recommended by this Reddit comment: https://www.reddit.com/r/Bazzite/comments/1fn59il/comment/n68c7mr/
It works as expected. Maybe it's a motherboard issue?

**Comment by andyschmid** [comment]
Unfortunately with the latest 43.20251029 version I'm also still running into issues on resume, same problem as before however I suspect the cause is different since xonedo code is current.

> Perhaps there is a different issue because plugging in the dongle into the BIOS flashback USB port as recommended by this Reddit comment: https://www.reddit.com/r/Bazzite/comments/1fn59il/comment/n68c7mr/ It works as expected. Maybe it's a motherboard issue?

I was hopeful, but this did not resolve the issue for me. I iterated through every USB port on my system with no success.

**Comment by andyschmid** [comment]
One last update with progress. I suspected this was hardware specific, so I transferred my Bazzite install to a different motherboard to test. Sure enough, the controller worked on resume.

Back to the original motherboard.. digging through BIOS settings I noticed an ACPI setting for "USB Device Power On (USB32_3)". With this option enabled, and plugging the xbox dongle into the specific USB3 port (2 or 3) on the motherboard, the controller is successfully detected on resume after suspend!

Note: Must have the latest xonedo driver in Bazzite 43 (tested on 43.20251102)

I hope this info helps others with the same problem.

**Comment by dabbott12** [comment]
I just installed the latest version of bazzite deck amd with game mode. This was happening to me. 

I resolved it by checking each usb port on back of my mobo. One by one. It was the second-last one to try. Now it’s working properly. 

Note - for me it wasn’t a blue port or the bios flashback port. It was a random black port, bottom left. 

Gigabyte B650I Ultra

**Comment by tibia1426** [comment]
I probably found a solution. Uploaded it here:
https://github.com/tibia1426/xbox-dongle-suspend-fix
Perhaps that can help someone.

**Comment by nabbl** [comment]
Doesn't work for me at least. First of all now I can't resume the system by turning on the controller. Then even after resuming manually the controller won't connect to the dongle at all

**Comment by tibia1426** [comment]
> Doesn't work for me at least. First of all now I can't resume the system by turning on the controller. Then even after resuming manually the controller won't connect to the dongle at all

I'm sorry to hear that. Thanks for the feedback. The solution worked for me at first, but I later realized it wasn't reliable; I still have to unplug and replug the dongle every now and then. I’ve given up on investigating it further for the time being and found a different workaround using a smart plug that automatically toggles the USB hub on and off. That works for me in my home theater setup, where I have everything automated. Maybe someone will continue working on a fix eventually—it really is an annoying problem.
