### ISSUE TITLE
Waking from suspend doesn't work with Nvidia Gnome

### ISSUE THREAD

**Issue by pradaker** [ublue-os/bazzite#2437]
### Describe the bug

I had been using Bazzite with KDE Plasma for a few months without issue. Yesterday, I decided to reinstall Bazzite but this time with Gnome, and most things have been fine. However, I am now not able to wake my PC from sleep. When I try, my display powers on for a brief moment, and then shuts off. The PC still has power, but it's not connected to the network, my keyboard/mouse doesn't seem to do anything, and even the power button does nothing unless I hold it down to forcefully shut it off.

System logs: https://paste.centos.org/view/85e837b0

System info: https://paste.centos.org/view/9f1ff574

### What did you expect to happen?

I expected the system to wake up and resume

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable
                   Digest: sha256:e8fdf9440b2231b75939652c21c3134a43f05135cbe4a547d1f2a5423ca01913
                  Version: 41.20250325 (2025-03-25T20:32:46Z)
          LayeredPackages: openrazer-daemon

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:9459dfc02f5d3c4bb9aba135333002e7021cb364e435fa51eacdca52e41ff72e
                  Version: 41.20250325 (2025-03-25T20:29:21Z)
          LayeredPackages: openrazer-daemon
```

### Hardware

Mobo: Asus ROG STRIX B650E-F Gaming WiFi
CPU: AMD Ryzen 9 7900X
GPU: Nvidia GeForce RTX 4090
RAM: 32GB

### Extra information or context

I didn't change any hardware during the switch from KDE Plasma to Gnome

**Comment by tduarte** [comment]
Installed Bazzite last night and I'm having the same issue.

**Comment by SanelessOne** [comment]
I wonder if you're having the same issue as me

https://github.com/ublue-os/bazzite/issues/2429

**Comment by natesevn** [comment]
FWIW, I have the same issue with `bazzite-gnome-nvidia-open`. I've also encountered the same with the KDE version `bazzite-nvidia-open`. It sounds like there was an issue with the `MT7922` Wifi card module that was [fixed as of Linux 6.12.8](https://bbs.archlinux.org/viewtopic.php?id=295916), but I'm still seeing it on Linux 6.13.7.

**Comment by tduarte** [comment]
@natesevn I’m running an Intel WiFi card, it looks like the only common denominator is the NVIDIA gpu.

**Comment by natesevn** [comment]
I was browsing through more user issues and came across this one which perfectly describes what I'm seeing: https://github.com/ublue-os/bazzite/issues/1904

Interestingly enough, it repros on AMD GPUs too.

**Comment by HopeSilent** [comment]
Can also confirm this issue is present for me on bazzite gnome with nvidia closed. It's running on a Ryzen 5 5600T in a Asrock B450m Pro4 with a GTX 1070. No ability to resume from suspend (no video output), have to hold the power button to force it off and then freshly boot up. This [post]((https://old.reddit.com/r/Fedora/comments/1epr6eg/black_screen_on_sleepwake_bazzite/)](url)) by Radioactive_Doomer on Reddit appears to discuss a similar issue that was resolved by doing the following:

"In case anyone else has this issue I fixed it. It was combination of AMD IOMMU making the gfx card inaccessible and some pci device controller triggering wake up.

I set amd_iommu=off in the GRUB command line options and used /proc/acpi/wakeup to find the offending device and disable wake signals."

This is the only reference I've found to the issue, indicating it was something to do with IOMMU, which I've already verified is disabled in my BIOS.

**Comment by Colcobau** [comment]
Having the exact same issue on my machine for the last couple of weeks. This only started recently, and was not an issue before.

![Image](https://github.com/user-attachments/assets/ceffcb1d-bfb0-49f8-8e0f-7418c1fe9b57)

Turning off IOMMU is not really an option for me.

**Comment by kumail-r** [comment]
@Colcobau I see you might have missed the solution [linked](https://bbs.archlinux.org/viewtopic.php?pid=2044189#p2044189) in the issue by OP, I just tried it and it worked for me (similar background, this problem started a few weeks ago on my system with an RTX 3090 + Ryzen 7000 CPU).

Instructions:
1. Create `/usr/local/bin/suspend-gnome-shell.sh` and put this script in it: 
```bash
#!/bin/bash

case "$1" in
    suspend)
        killall -STOP gnome-shell
        ;;
    resume)
        killall -CONT gnome-shell
        ;;
esac
```

2. Do the same for `/etc/systemd/system/gnome-shell-suspend.service`:

```TOML
[Unit]
Description=Suspend gnome-shell
Before=systemd-suspend.service
Before=systemd-hibernate.service
Before=nvidia-suspend.service
Before=nvidia-hibernate.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/suspend-gnome-shell.sh suspend

[Install]
WantedBy=systemd-suspend.service
WantedBy=systemd-hibernate.service
```

3. Do the same for `/etc/systemd/system/gnome-shell-resume.service`:

```TOML
[Unit]
Description=Resume gnome-shell
After=systemd-suspend.service
After=systemd-hibernate.service
After=nvidia-resume.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/suspend-gnome-shell.sh resume

[Install]
WantedBy=systemd-suspend.service
WantedBy=systemd-hibernate.service
```

4. Finally, run these commands:

```shell
systemctl daemon-reload
systemctl enable gnome-shell-suspend
systemctl enable gnome-shell-resume
```

**Comment by Colcobau** [comment]
@kumail-r Oh, I didn't miss it, and I can do that no problem, it's just that the whole point of atomic desktops is NOT having to do these things. But I guess as a workaround I might give it a go.

**Comment by Colcobau** [comment]
Worth noting, I tried the suggested fix and the issue persists.

**Comment by fpatrick** [comment]
I am also having the this problem for 2 weeks (rtx 3060 ti). I thought it was related to a new nvidia driver, if gnome have such a big issue for weeks I would say nvidia's gpu owners should never use it. unfortunately.

**Comment by Imasu** [comment]
I confirm that the steps noted by @kumail-r resolved the issue for me, provided to make the shell executable : 
`sudo chmod +x /usr/local/bin/suspend-gnome-shell.sh`

**Comment by HopeSilent** [comment]
> I confirm that the steps noted by [@kumail-r](https://github.com/kumail-r) resolved the issue for me, provided to make the shell executable : `sudo chmod +x /usr/local/bin/suspend-gnome-shell.sh`

Thank you, @Imasu, I definitely face-palmed reading that. Script works as intended with appropriate privileges. I also see dramatic improvement in the amount of time it takes to go to sleep as it, presumably, is no longer fighting to do so.

Hopefully this won't be necessary in the future?

**Comment by Colcobau** [comment]
> I confirm that the steps noted by [@kumail-r](https://github.com/kumail-r) resolved the issue for me, provided to make the shell executable : `sudo chmod +x /usr/local/bin/suspend-gnome-shell.sh`

I too facepalmed into the sun. Forgot to make it executable.

**Comment by fpatrick** [comment]
> I confirm that the steps noted by [@kumail-r](https://github.com/kumail-r) resolved the issue for me, provided to make the shell executable : `sudo chmod +x /usr/local/bin/suspend-gnome-shell.sh`

Thank you and @kumail-r now it works 🥳

**Comment by natesevn** [comment]
I also want to confirm that following the steps outlined by @kumail-r and @Imasu fixed it for me. I'm now able to suspend 👍

**Comment by Sokhii** [comment]
Hey, I am also having this issue on Mini PCs running an AMD APU. I am currently running stock steam OS and don’t experience this so I believe it’s an issue specifically with bazzite. Hoping for an official fix soon.

**Comment by mitterman2** [comment]
using the suggested fix only fixed the problem that bazzite would suspend, it does now, but it is not waking up from suspend. 
amd cpu, nvidia gpu. 
before, the system would not enter the suspend state with fans spinning and i had to hard reboot every time. now it at least shuts the system down but still needs a hard reboot to revive.

**Comment by fjkorol** [comment]
> [@Colcobau](https://github.com/Colcobau) I see you might have missed the solution [linked](https://bbs.archlinux.org/viewtopic.php?pid=2044189#p2044189) in the issue by OP, I just tried it and it worked for me (similar background, this problem started a few weeks ago on my system with an RTX 3090 + Ryzen 7000 CPU).
> 
> Instructions:
> 
> 1. Create `/usr/local/bin/suspend-gnome-shell.sh` and put this script in it:
> 
> #!/bin/bash
> 
> case "$1" in
>     suspend)
>         killall -STOP gnome-shell
>         ;;
>     resume)
>         killall -CONT gnome-shell
>         ;;
> esac
> 2. Make the script executable (thanks [@Imasu](https://github.com/Imasu)):
> 
> sudo chmod +x /usr/local/bin/suspend-gnome-shell.sh
> 3. Do the same for `/etc/systemd/system/gnome-shell-suspend.service`:
> 
> [Unit]
> Description=Suspend gnome-shell
> Before=systemd-suspend.service
> Before=systemd-hibernate.service
> Before=nvidia-suspend.service
> Before=nvidia-hibernate.service
> 
> [Service]
> Type=oneshot
> ExecStart=/usr/local/bin/suspend-gnome-shell.sh suspend
> 
> [Install]
> WantedBy=systemd-suspend.service
> WantedBy=systemd-hibernate.service
> 4. Do the same for `/etc/systemd/system/gnome-shell-resume.service`:
> 
> [Unit]
> Description=Resume gnome-shell
> After=systemd-suspend.service
> After=systemd-hibernate.service
> After=nvidia-resume.service
> 
> [Service]
> Type=oneshot
> ExecStart=/usr/local/bin/suspend-gnome-shell.sh resume
> 
> [Install]
> WantedBy=systemd-suspend.service
> WantedBy=systemd-hibernate.service
> 6. Finally, run these commands:
> 
> systemctl daemon-reload
> systemctl enable gnome-shell-suspend
> systemctl enable gnome-shell-resume

Thanks!, in bazzite gnome works great, somethink similar fird bazzite kde plasma?, i have eventually freezes using kde.

**Comment by xalt7x** [comment]
GNOME bug reports:

- https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5772
- https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/8292

Thread on NVIDIA forums: https://forums.developer.nvidia.com/t/trouble-suspending-with-510-39-01-linux-5-16-0-freezing-of-tasks-failed-after-20-009-seconds/200933/12

**Comment by ThomasChiodini** [comment]
I have the same issue and am trying to implement the fix listed but nothing let's me write to the folder. Ive tried going to root and changing permissions, but I cant seem to create the file to even start the fix. Any help?

**Comment by xalt7x** [comment]
@ThomasChiodini 
> I have the same issue and am trying to implement the fix listed but nothing let's me write to the folder.

Which folder exactly? What is an error? Steps from [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/8292#note_2444825) should work.

**Comment by wammax** [comment]
The @kumail-r/@Imasu workaround seems to have solved my suspend problem as well. Thanks alot =)

Though after resuming I get weird graphical glitches in the OS gui. Some of them seems to be a bit random, such as artifacts in the top right "settings menu". The system gui font seems to break in a consitent way though, "distorting" every a and s character in the system menus directly connected to the desktop (such as the bazzite menu in the top left corner and the show apps view. No problems though in any applications or windows (such as settings, store, terminal and so on). Need to reboot to go back to normal. Running an AMD CPU (5900X) and an Nvidia GPU (RTX3080). Anyone else experiencing the same thing?

Edit: the problem seems to have solved itself somwhow after some restarts... Atleast I can no longer reliably reproduce the graphical glitches...

**Comment by nickzyqh** [comment]
The workaround worked for me for a while, but it came back recently. On hitting suspend, the screen would turn off but any mouse movement would wake it back up. 

I think this indicates that the services are enabled, right?
```
❯ systemctl status gnome-shell-suspend
○ gnome-shell-suspend.service - Suspend gnome-shell
     Loaded: loaded (/etc/systemd/system/gnome-shell-suspend.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)

Aug 20 12:19:25 bazzite systemd[1]: Finished gnome-shell-suspend.service - Suspend gnome-shell.
Aug 20 21:32:32 bazzite systemd[1]: Starting gnome-shell-suspend.service - Suspend gnome-shell...
Aug 20 21:32:32 bazzite systemd[1]: gnome-shell-suspend.service: Deactivated successfully.

```

```
❯ systemctl status gnome-shell-suspend
○ gnome-shell-suspend.service - Suspend gnome-shell
     Loaded: loaded (/etc/systemd/system/gnome-shell-suspend.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)

Aug 20 12:19:25 bazzite systemd[1]: Finished gnome-shell-suspend.service - Suspend gnome-shell.
Aug 20 21:32:32 bazzite systemd[1]: Starting gnome-shell-suspend.service - Suspend gnome-shell...
Aug 20 21:32:32 bazzite systemd[1]: gnome-shell-suspend.service: Deactivated successfully.

```

**Comment by renankaic** [comment]
I'm having the same issue with Bazzite KDE
Unfortunately, I don't even know where should I start in order to fix this issue 😔

**Comment by TG-March** [comment]
> I'm having the same issue with Bazzite KDE Unfortunately, I don't even know where should I start in order to fix this issue 😔

Same, Intel 13600K, Nvidia 4070 and Bazzite Nvida KDE desktop image.

Have disabled automatically going into sleep for now... as my PC wakes up with a black screen. It's not possible to switch to another session with CTRL+ALT+F[1-6] keys so it's not just the desktop environment that's borked.

**Comment by grantland** [comment]
I'm having a similar issue and tried the `gnome-shell-suspend/resume` solution, however, my system is unable to find the process `gnome-shell`. Is anyone else having a similar issue?

FWIW my issue is waking from sleep from within Game Mode sometimes doesn't send a video signal and maybe the problem/solution described here is for Desktop Mode only?

```
$ systemctl status gnome-shell-suspend
× gnome-shell-suspend.service - Suspend gnome-shell
     Loaded: loaded (/etc/systemd/system/gnome-shell-suspend.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Thu 2026-02-05 23:16:20 PST; 13min ago
 Invocation: f18e22c857f74579a4e5e47fccd2fa9e
    Process: 5774 ExecStart=/usr/local/bin/suspend-gnome-shell.sh suspend (code=exited, status=1/FAILURE)
   Main PID: 5774 (code=exited, status=1/FAILURE)
   Mem peak: 1.7M
        CPU: 16ms

Feb 05 23:16:20 steammachine systemd[1]: Starting gnome-shell-suspend.service - Suspend gnome-shell...
Feb 05 23:16:20 steammachine suspend-gnome-shell.sh[5781]: gnome-shell: no process found
Feb 05 23:16:20 steammachine systemd[1]: gnome-shell-suspend.service: Main process exited, code=exited, status=1/FAILURE
Feb 05 23:16:20 steammachine systemd[1]: gnome-shell-suspend.service: Failed with result 'exit-code'.
Feb 05 23:16:20 steammachine systemd[1]: Failed to start gnome-shell-suspend.service - Suspend gnome-shell.
$ systemctl status gnome-shell-resume
× gnome-shell-resume.service - Resume gnome-shell
     Loaded: loaded (/etc/systemd/system/gnome-shell-resume.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Thu 2026-02-05 23:22:47 PST; 7min ago
 Invocation: d8b6671691b649bba68c102ac07e1750
    Process: 6002 ExecStart=/usr/local/bin/suspend-gnome-shell.sh resume (code=exited, status=1/FAILURE)
   Main PID: 6002 (code=exited, status=1/FAILURE)
   Mem peak: 1.7M
        CPU: 17ms

Feb 05 23:22:47 steammachine systemd[1]: Starting gnome-shell-resume.service - Resume gnome-shell...
Feb 05 23:22:47 steammachine suspend-gnome-shell.sh[6008]: gnome-shell: no process found
Feb 05 23:22:47 steammachine systemd[1]: gnome-shell-resume.service: Main process exited, code=exited, status=1/FAILURE
Feb 05 23:22:47 steammachine systemd[1]: gnome-shell-resume.service: Failed with result 'exit-code'.
Feb 05 23:22:47 steammachine systemd[1]: Failed to start gnome-shell-resume.service - Resume gnome-shell.
$ ps aux | grep gnome
grantla+    3669  0.0  0.0 168428  7580 ?        Ssl  22:56   0:00 /usr/libexec/at-spi2-registryd --use-gnome-session
grantla+    6970  0.0  0.0 231268  2588 pts/0    S+   23:31   0:00 grep --color=auto gnome
```
