### ISSUE TITLE
Screen flickering: AMD Video Card, 240 hz monitor, VRR, HDR

### ISSUE THREAD

**Issue by ghostklart** [ublue-os/bazzite#2917]
### Describe the bug

After installing and updating to latest stable build, the screen starts flickering black randomly.

Monitor - Samsung Odyssey G6 240 hz.
Video Card - AMD Radeon 7900 XTX
DE - KDE

What have been done to try to fix:

- install LACT. Set up OC for GPU Manual/Compute - no luck
- set Adaptive Sync: Never, HDR: off - no luck
- set Adaptive Sync: Never, HDR: on - no luck
- set Adaptive Sync: Always, HDR: on - works, but the interface becomes laggy (over X11 windows)

### What did you expect to happen?

No flickering or stuttering when using OS (on desktop and in games)

### Output of `rpm-ostree status`

```shell
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:9db015e8b806d902ff5f7913954d8d5f1d6a41c6f455f9e66e2b0586890f5de1
                  Version: 42.20250715.1 (2025-07-15T23:09:06Z)
          LayeredPackages: openrazer-daemon
```

### Hardware

<img width="1027" height="564" alt="Image" src="https://github.com/user-attachments/assets/f5eb1604-7d8f-4b64-9e98-e5e353e90d1b" />

**Comment by federico-moretti** [comment]
I think I have a similar issue: horizontal stripes/artifacts keeps flashing as soon as I installed Bazzite 42. I've rolled back to Bazzite 41 and everything is fine now.

**System:**
Processors: 12 × AMD Ryzen 5 9600X 6-Core Processor
Graphics Processor: AMD Radeon RX 7900 XT
Monitor: Gigabyte M32U 4k at 144Hz

**Comment by ghostklart** [comment]
issue still present on 42.20250804

sadly similar situations happen on other dsitros. Is there reported kernel issue on AMD GPUs GPU is rather old by now)?

**Comment by Ronin15** [comment]
I have the similar iissue with Bazzite 42 dx. I have minor screen flickering on first logon. If I change the refresh rate the issue goes away until resume from sleep.

<img width="1120" height="557" alt="Image" src="https://github.com/user-attachments/assets/a995cd5a-c7f7-488d-b750-c3b0b6304658" />

**Comment by federico-moretti** [comment]
I updated to the image `43.20251029` and everything seems to work fine now, no more flickering.

<img width="1458" height="614" alt="Image" src="https://github.com/user-attachments/assets/bd054334-d217-4825-b8dd-80cba982adf0" />

**Comment by ghostklart** [comment]
after some time got back on bazzite from Windows

<img width="910" height="514" alt="Image" src="https://github.com/user-attachments/assets/6a0bdd8b-9a3c-443a-ad5b-7f9932feca0e" />

the issue it not gone, screen flickering seems to be back on anything above 120hz. plus very scary artifacts started appearing on the bottom of the screen.

same behavior was caught with windows as well and it was solved (on the same hardware) with the following registry edit: [mpo_disable.zip](https://github.com/user-attachments/files/23433023/mpo_disable.zip)

Gonna keep dualbooting until fixed (or BF6 starts working on Linux smiley face).

**Comment by chase-robbins** [comment]
Same issue but on NVIDIA Card, 240hz display on my laptop.

<img width="2022" height="1100" alt="Image" src="https://github.com/user-attachments/assets/01a9095a-cf48-43f4-b6c9-b88129bcf844" />

**Comment by Skauroki** [comment]
Same issue On Samsung G3 24 inch monitor , almost every game flickers , on 42 also on 43 versions. I use 165hz , changing to 144 sometimes fixes , but device usually crashes. or messes up my outputs. Full AMD system

<img width="923" height="533" alt="Image" src="https://github.com/user-attachments/assets/9e112da0-02fe-4cb7-9c26-e8908a2aef84" />

**Comment by ghostklart** [comment]
> Same issue but on NVIDIA Card, 240hz display on my laptop.
> 
> <img alt="Image" width="2000" height="1100" src="https://private-user-images.githubusercontent.com/11085836/518911513-01a9095a-cf48-43f4-b6c9-b88129bcf844.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjkyNDYwNTMsIm5iZiI6MTc2OTI0NTc1MywicGF0aCI6Ii8xMTA4NTgzNi81MTg5MTE1MTMtMDFhOTA5NWEtY2Y0OC00M2Y0LWI2YzktYjg4MTI5YmNmODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTI0VDA5MDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5M2I3ZDc0YjE3Y2QwYTYwNmMwMDMxNGU0ZGFhN2VmMmZhZmNlZDJjMTAxNTUyZTM0MDBmZDQ2NjRiMTM0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VA-BJc1G6tn4U1rRHNY_yMTZy9Pcy69ObkwqsctRfJk">
Just so you know, for the Nvidia card you’d better open a separate issue, since Nvidia and Amd OS builds are totally different

**Comment by 3dsonsuce** [comment]
Have you found a solution OP? To this day I still have this problem.

<img width="850" height="365" alt="Image" src="https://github.com/user-attachments/assets/f488eb2b-3b70-4999-8bd4-9d73f97e4b16" />
