### ISSUE TITLE
Xbox Rog Ally X - Steam + (key) shortcuts not working, mouse toggle not working

### ISSUE THREAD

**Issue by pbocek** [ublue-os/bazzite#3351]
### Describe the bug

On Xbox Rog Ally X, shortcuts like Steam + X does not trigger keyboard, or Steam + LB does not trigger magnifier. Also holding the top right button does vibrate once, but does not switch to mouse mode (nor in desktop, steam or game)

### What did you expect to happen?

I would expect that these combos/shortcuts trigger the actions

### Session Logs

```shell
https://paste.centos.org/view/96232234
```

### Hardware

Xbox Rog Ally X

**Comment by antheas** [comment]
The mouse toggle is already fixed in unstable. Steam + keys require you select the armoury swap option in hhd settings

**Comment by pbocek** [comment]
> The mouse toggle is already fixed in unstable. Steam + keys require you select the armoury swap option in hhd settings

After switching it works fine as you say, but then the select/start keys are too far for me, is it possible to implement without switching?

**Comment by antheas** [comment]
Others have suggested I add an option to use the normal xbox button for steam, so that setting needs to be reworked

But right now we are focusing on fedora 43

**Comment by pbocek** [comment]
> Others have suggested I add an option to use the normal xbox button for steam, so that setting needs to be reworked
> 
> But right now we are focusing on fedora 43

That would work as well! Thank you!

**Comment by pbocek** [comment]
the mouse toggle is still not working for me in testing and stable, holding top right vibrates but doesn't toggle the mouse

**Comment by antheas** [comment]
The mouse toggle works on my Xbox Ally. Make sure you are up to date

**Comment by pbocek** [comment]
yesterday evening I tried latest testing 43, and then switched to stable 43. Holding the top right button gives a short vibration after a second, but doesn't switch the input for me. Same vibration happens after consequent holdings.

**Comment by pbocek** [comment]
I’ve pressed it multiple times and generated bug report. https://paste.centos.org/view/60ae9bbc

![Image](https://github.com/user-attachments/assets/857c0cd9-11a5-438a-9bc5-788a3316de2e)

**Comment by Ansel-Mah** [comment]
> 其他人建议我添加一个选项，使用正常的xbox按钮进行蒸汽，因此该设置需要重新处理
> 
> 但现在我们专注于fedora 43

I also hope to be able to use the Xbox buttons for Steam, and I have also encountered the issue where desktop pointer control doesn’t work.
I know you fixed many issues with the Xbox Ally in the Fedora 43 system, and I’m very grateful to you for that.
However, I also hope to be able to make more use of the Xbox buttons in the next version. If this can be achieved, then Bazzite OS will be perfect for me!

**Comment by pbocek** [comment]
mouse toggle still not working for me.
https://paste.centos.org/view/ddf7a1b2

43.20251114.1 stable

**Comment by lnuyl** [comment]
> The mouse toggle is already fixed in unstable. Steam + keys require you select the armoury swap option in hhd settings

Hi Ive been trying to update into the unstable build on xbox ally x, but the handheld deamon doesnt let me and neither does the terminal in desktop mode do you think you could help me update it?

**Comment by bashbarnard** [comment]
Same bug on the latest build with the Xbox rog ally NON x. I can hold the button, get the vibration to confirm that the switch has happened and no mouse.

**Comment by sebasjoa** [comment]
Still the xbox buttons only opens HHD. The armory crate its for that i swear

**Comment by dov-vai** [comment]
Mouse mode toggle doesn't work but it does vibrate. One workaround to get mouse working is switch to steam controller emulation in hhd and turn on handheld mode. Then you can use the right stick as mouse in desktop mode. Steam has to be in background, and might need to turn it on once after enabling.
