### ISSUE TITLE
RogXbox Ally X Sleep mode doesn't work properly.

### ISSUE THREAD

**Issue by suyoumo** [ublue-os/bazzite#3487]
### Describe the bug

I have successfully installed the Bazzite OS on my ASUS ROG Xbox Ally X. The installation process went smoothly overall, but there is one major issue: Sleep mode doesn't work properly.
By "doesn't work properly", I mean the screen turns off (that's half the expected behavior). However, after tapping the screen to wake the device, it fails to wake up normally—it briefly comes back to life for a few seconds before turning the screen off again.
I wait a few seconds and press the power button again, expecting it to resume normally. The only way to recover the device is to force it off and then boot back up, which restores the Bazzite OS to normal.
I have updated the BIOS to the latest version, and the controller firmware as well as all other firmware updates have been applied. My device is equipped with a Ryzen Z2 Extreme processor.

### What did you expect to happen?

The device should enter sleep mode when the power button is pressed, and exit sleep mode when the power button is pressed again while in sleep.

### Session Logs

```shell
I am not sure if the session logs would be useful, because if I have to force the device off to recover it, the session logs might have been lost.
```

### Hardware

ASUS ROG Xbox Ally X
24GB On-board System Memory
2TB NVMe SSD
Latest firmware & BIOS installed

### Extra information or context

I hope this issue can be fixed.

**Comment by antheas** [comment]
This is fixed by the version that came out today

**Comment by suyoumo** [comment]
> This is fixed by the version that came out today

1114 stable version ？

**Comment by antheas** [comment]
Yeah

**Comment by arcataroger** [comment]
Just tried the latest version (if that's the Steam Deck image on bazzite.gg) and this is still broken. Pushing the power causes sleep, but nothing can wake it back up again. Must force shut down by holding down power and then start it again.

Same issue with SteamOS, for what it's worth.

**Comment by ilulale** [comment]
I installed the latest version today from bazite.xyz , the issue persists

**Comment by probablyhades** [comment]
Installed latest version to an ROG Xbox Ally as well today, still no fix for this issue.

**Comment by tanwwg** [comment]
Sleep and resume works for me on the latest bazzite, but not on steamos 3.8 or 3.9 (it will not resume).
