### ISSUE TITLE
GNOME: Padding around items in status bar is incorrect

### ISSUE THREAD

**Issue by tedgravlin** [ublue-os/bazzite#3550]
### Describe the bug

<img width="129" height="60" alt="Image" src="https://github.com/user-attachments/assets/58ac9bdb-5444-45e0-933c-e9c02e132112" />-

<img width="184" height="107" alt="Image" src="https://github.com/user-attachments/assets/e8ec94b6-50ba-4945-b0cb-7c2feb9d49be" />

As seen in the screenshots above, the padding for some of the sections in the status bar is too small, which leads to icons overflowing out of the container. This behavior does not occur on Fedora Workstation using GNOME.

### What did you expect to happen?

The padding should be increased to accommodate the icons.

### Session Logs

```shell
[redacted]
```

### Hardware

Framework Laptop 13 11th Gen Intel Core i5

**Comment by KyleGospo** [comment]
This is intentional, without it the tray icon extension takes up way, way too much space and the space between icons is inconsistent.

**Comment by tedgravlin** [comment]
Hi @KyleGospo, thanks for the reply!

Is there a way to have the reduced padding only apply when the tray icon extension is enabled? I'm not using it on my end. If not, that's okay, I'm just curious

**Comment by KyleGospo** [comment]
It's a shell theme, if you switch to the default then you'll have default padding.

**Comment by tedgravlin** [comment]
That worked, thank you so much!

For any future readers experiencing the same issue, here's how to switch to the default theme:

1. Open the "Extension Manager" app
2. Click the gear icon next to "User Themes"
3. Select the "Default" theme
4. Log out, log back in
5. Padding is fixed

**Comment by airtonix** [comment]
> It's a shell theme, if you switch to the default then you'll have default padding.

@KyleGospo should this not then be the default setup? 

Be me 

Be me in front of new linux user 

Be me installing Bazzite

Be me ABSOLUTE UP MAXXING LINUX

Be me showing them the desktop

Be them pointing out how crap the top bar looks

Be me with no answer

Be them saying "Oh well it was fun while it lasted, I guess this isn't the year of the linux desktop after all"

**Comment by airtonix** [comment]
btw switching to `default` still doesn't fix the problem. 

<img width="182" height="69" alt="Image" src="https://github.com/user-attachments/assets/39952442-b956-4306-b0ff-0c50666447a7" />

**Comment by airtonix** [comment]
Installing "Just Perfection" then switching to `minimal` preset then back to `default` preset fixed it

<img width="182" height="69" alt="Image" src="https://github.com/user-attachments/assets/a9452565-9f88-4242-a61e-3bbfb6cd0ace" />
