### ISSUE TITLE
xone driver

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#970]
Can we get an Updated Version of Xone Driver
i have a GameSir G7 SE and the Audio Port doesnt work, but on the latest version works it works fine, is there a way to get the latest version so i can use the headphone port on my controller.

**Comment by massatt212** [comment]
idk if you want to test this out also, i change the file system to ext4 and i no longer get the steam hanging or very long reboots or startups, i notice btrfs gave me problems with apex sometimes, but ext4 fixed it so far ill test some more.

**Comment by massatt212** [comment]
is there a way to install xone driver or can we get the latest xone driver as an option?

**Comment by massatt212** [comment]
i saw akmods can instal xonedo

`[xonedo](https://github.com/BoukeHaarsma23/xonedo/) - xbox one controller USB wired/RF driver modified to work along-side xpad (akmod from [ublue-os/akmods copr](https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/))`

how do i run this, its kinda confusing

**Comment by HikariKnight** [comment]
xone is provided by [ublue-os/akmods](https://github.com/ublue-os/akmods) which just builds https://github.com/BoukeHaarsma23/xonedo/

so it will be reliant on when that updates since we rely on xpad working alongside xone.

Considering the last commit was last week and this issue is from April i would guess your controllers audio port should work now?

**Comment by massatt212** [comment]
Ok I'll try when I reinstall

**Comment by massatt212** [comment]
# sry this reply took very long, the audio still doesn't work, and my original or gamsire controller doesn't light up, so I know the come driver is not being used

**Comment by massatt212** [comment]
> xone is provided by [ublue-os/akmods](https://github.com/ublue-os/akmods) which just builds https://github.com/BoukeHaarsma23/xonedo/
> 
> so it will be reliant on when that updates since we rely on xpad working alongside xone.
> 
> Considering the last commit was last week and this issue is from April i would guess your controllers audio port should work now?

I decided to install another is to test out the xonedo drivers and my audio from controller is working, so I dont think you are using the latest version of xonedo.

**Comment by massatt212** [comment]
Ok I'll go check now

**Comment by massatt212** [comment]
rpm -q xone-kmod-common
`xone-kmod-common-0.0.git.115.fdbb71f1-1.fc40.noarch`

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:89f8cd6c041242f31da8362ad97637fc68fa88515b83aef69e70c4f3d0854de7
                  Version: 40.20240624.0 (2024-06-24T17:13:00Z)
          LayeredPackages: goverlay
            LocalPackages: lact-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:3c8f282ad7eb9c1feb1aecb37a17e455131171dc30cd69d704a93d783cfee6aa
                  Version: 40.20240624.0 (2024-06-24T16:39:32Z)
          LayeredPackages: goverlay
            LocalPackages: lact-0.5.4-0.x86_64

**Comment by HikariKnight** [comment]
yeah that is the newest xonedo, last build was 29 days ago and last commit was 39 days ago

**Comment by massatt212** [comment]
Maybe it's not active

**Comment by HikariKnight** [comment]
> Maybe it's not active

connect the controller to bluetooth and `lsmod | grep xone`

**Comment by massatt212** [comment]
Gamsir controller don't have bluetooth it's cable and cable doesn't have audio support

**Comment by massatt212** [comment]
> > Maybe it's not active
> 
> connect the controller to bluetooth and `lsmod | grep xone`

https://www.amazon.com/GameSir-Controller-Xbox-Windows-Joysticks-X/dp/B0C7GW9F88/ref=sr_1_3?crid=1MJXRSDJFKT5M&dib=eyJ2IjoiMSJ9.9kvKD-L2H7SyGR1cb51jEkmMH-suXj8oRZYQ6ZSRpxWwQgvUVyzbX87cBR1LQfDjNzlna8e_o8hbWDbPw8BcCOSOlV2IK_czS2VSxBSA8PkamOkhMRHnTZuzUN8AomYRge4mB7Dqnvr9VYC65vnEx3WknApFLJpKkovmXBiffmnocGjre6EFO-mhBDpPg_v_yBy0S1JH3GSBW7b0sBvNp1MNtYoS5pKLXOo_pO2WxVQ.BdOVNBmJeFOzkBO-q6SUPIwdMLM5ys8WaAzsEhS-cSQ&dib_tag=se&keywords=gamesir+g7+se+xbox+controller&qid=1719445124&sprefix=gamesir+se%2Caps%2C182&sr=8-3

**Comment by KyleGospo** [comment]
This is expected behavior, our xone driver has the USB support removed from it. This allows it to coexist with xpad. If we didn't do that we would lose support for a ton of wired controllers that people commonly use.

**Comment by HikariKnight** [comment]
Checked with the team, its caused by our xone having the wired component removed, because it would break **a ton** of controllers that only xpad supports.

It is not something we can support since it will be the choice of breaking almost everyones controllers or get working audio over wired xbox controllers (and it can not be made an ujust toggle as xone and xonedo cannot exist on the same system).

**Comment by massatt212** [comment]
ok

**Comment by cvtele** [comment]
@KyleGospo Is there a recommended work around for those of us with a wired xbox style controller?

**Comment by KyleGospo** [comment]
The only work around if you must have this feature is to make a custom image. We can't ship this because it breaks far more controllers than it fixes.

**Comment by cvtele** [comment]
That's what I thought. Thanks for the confirmation.
